        <!-- Fecha DIV Container-Fluid -->
        </div>
        
            
    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace();
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    
    <!-- JS -->
    <script type="text/javascript" src="<?php echo HOME ?>js/jquery-3.3.1.min.js"></script>
    <script type="text/javascript" src="<?php echo HOME ?>js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo HOME ?>js/showmenu.js"></script>
    <script type="text/javascript" src="<?php echo HOME ?>js/dashChart.js"></script>
    <script type="text/javascript" src="<?php echo HOME ?>js/scripts.js"></script>
   
    </body>
</html>