<!DOCTYPE html>
<html lang="pt-BR" dir="ltr">
  <head>
      <meta http-equiv="X-UA-Compatible" content="IE=Edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta charset="utf-8">

		<title>Web Login</title>

      <!-- Sem Javascript - <noscript> </noscript> -->

    <!-- Icone (SVG - Todos os tamanhos) -->
    <link rel="icon" href="<?php echo HOME ?>/img/tree-icon.svg" sizes="any" type="image/svg+xml">

    <!-- CSS -->

    <link href="<?php echo HOME ?>css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo HOME ?>css/style.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">


  </head>

<body>
 <div class="container-fluid">