
  <div class="col-12 col-sm-12 col-md-12 col-lg-3 menu-info-user">

    <div class="row">

      <div class="col-4 col-sm-4 col-md-4 col-lg-4 img-user-fig">
          <div class="img-user-figcap">
              <span class="img-alter">Alterar</span>
          </div>
      </div>

      <div class="col-8 col-sm-8 col-md-8 col-lg-8">
        <p><strong>Janaína Dutra</strong><br>
                janainad.barbosa@gmail.com<br>
        </p>
        <button type="button" class="btn btn-outline-primary btn-sm">Meu perfil</button>
      </div>

    </div>

      <ul class="nav nav-pills nav-stacked flex-column nav-user-menu">
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModal"><span class="fa fa-table"></span>Acessos</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#"><span class="fa fa-sign-out"></span>Sair</a>
        </li>
      </ul>

    </div>