<!-- MENU -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark menu-nav">
          <a class="navbar-brand" href="<?php echo HOME ?>">
          <img src="/img/tree-icon.svg" width="60" height="60" alt="Web Login" title="Web Login">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
   
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Cadastro
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Centro de Custo</a>
              <a class="dropdown-item" href="#">Colaborador</a>

              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Cliente</a>
              <a class="dropdown-item" href="#">Fornecedor</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Departamentos
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Departamento 01</a>
              <a class="dropdown-item" href="#">Departamento 02</a>
              <a class="dropdown-item" href="#">Departamento 03</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Departamento 04</a>
              <a class="dropdown-item" href="#">Departamento 05</a>
              <a class="dropdown-item" href="#">Departamento 06</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Financeiro
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Relatório 01</a>
              <a class="dropdown-item" href="#">Relatório 02</a>
              <a class="dropdown-item" href="#">Relatório 03</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Relatório 04</a>
              <a class="dropdown-item" href="#">Relatório 05</a>
            </div>
          </li>

        </ul>

        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Pesquisa" aria-label="Search">
        </form>

          <!-- Menu User Logout -->
          <div class="col-12 col-sm-12 col-md-1 col-lg-1 nav-user-logout">
                <img class="img-responsive rounded-circle user" src="/img/jana.png" width="40px" height="40px" alt="Perfil Usuário" title="Perfil"><span class="fa fa-chevron-circle-down"></span>
                <div class="icon-menu"></div>
          </div>

      </div>
    </nav>
  <!-- Fim NAV/Menu -->