<!DOCTYPE html>
<html lang="pt-BR" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Web Login - Erro 404</title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo HOME ?>css/bootstrap.min.css" rel="stylesheet">

  </head>
   
  <body>

<div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Ops, há algo errado!</h1>
          <p>Página não encontrada, navegue pelo menu.</p>
        </div>
      </div>


 </body>
</html>